[build]
  command = "npm run build"  # 指定构建脚本
  functions = "out_functions"  # 指定Serverless函数的目录

# [build.environment]
#  NODE_VERSION = 18  # 指定Node.js版本

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_next/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"  # 配置CORS允许跨域请求
